[preview]
cache_dir = "$HOME/.cache/yazi"

[[plugin.prepend_previewers]]
name = "*.odt"
run  = 'piper -- odt2txt "$1"'

[[plugin.prepend_previewers]]
name = "*.docx"
run  = 'piper -- docx2txt "$1" -'

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" },
]
view = [{ run = 'imv "$@"', orphan = true, for = "unix" }]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "%1"', orphan = true, desc = "Open", for = "windows" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
]


[open]
rules = [
  { mime = "text/*", use = ["edit", "open"] },
  { mime = "video/*", use = ["play", "open"] },
  { mime = "image/*", use = ["view", "open"] },
  { name = "*.json", use = ["edit", "open"] },

  # Multiple openers for a single rule
  { name = "*.html", use = ["open", "edit"] },
  { name = "*.lua", use = ["edit"] },

  { mime = "application/zip", use = ["extract", "reveal"] },
  { mime = "application/gzip", use = ["extract", "reveal"] },
  { mime = "application/x-tar", use = ["extract", "reveal"] },
  { mime = "application/x-bzip", use = ["extract", "reveal"] },
  { mime = "application/x-bzip2", use = ["extract", "reveal"] },
  { mime = "application/x-7z-compressed", use = ["extract", "reveal"] },
  { mime = "application/x-rar", use = ["extract", "reveal"] },
  { mime = "*", use = ["open", "edit"] },
]
