#!/usr/bin/env bash

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    # SSH (stream)
    kitty +kitten icat --clear --stdin no --transfer-mode stream </dev/null >/dev/tty
else
    if [ -n "$TMUX" ]; then
        ueberzugpp cmd -s $UB_SOCKET -a remove -i PREVIEW
    fi
    # NO ssh (memory)
    kitty +kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty
fi
