#!/usr/bin/env bash

zoom_factor=$(hyprctl getoption cursor:zoom_factor -j | jq ."float")

if [[ $(printf "%0.f" "$zoom_factor") == 1 ]]; then
    hyprctl keyword cursor:zoom_factor 3
else
    hyprctl keyword cursor:zoom_factor 1
fi
